# Generated by Django 5.1.7 on 2025-04-02 19:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('template_content', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Repositories'},
        ),
        migrations.AddField(
            model_name='repository',
            name='forks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='repo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='repo_owner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repo_url',
            field=models.URLField(unique=True),
        ),
        migrations.CreateModel(
            name='GeneratedReadme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readmes', to='generator.repository')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('repository', 'version')},
            },
        ),
    ]
